### ISSUE TITLE
[Enhancement] Make a marketplace for community repositories

### ISSUE THREAD

**Issue by Ivanmatthew** [va1kio/commander#60]
Mabe this goes against your reasons for making commander in the first place, but I thought of that there's maybe a chance for players to publish their modular repository of extra commands and can share it to other people through a marketplace.

**Comment by va1kio** [comment]
We've actually discussed about this in our website redo plan a few days ago! But we decided to scrap it, mostly because of the overall cost to implement a fully-fledged marketplace system.

**How?**
Mostly because of how we want it to be, rather than relying on GitHub for downloading the command, we want to have a custom external server to place commands in rbxm file. That way, we can implement update reviewing process, and more.

However, with that being said, not only we need a server to handle the backend, but we also need a powerful file server and a database server as well, which means there will be **three** servers in total.

As Commander is open-source, completely free and does not have any actual backers to help us with funding, it is barely possible for us to afford the operating cost for those three servers.

**Comment by Ivanmatthew** [comment]
> We've actually discussed about this in our website redo plan a few days ago! But we decided to scrap it, mostly because of the overall cost to implement a fully-fledged marketplace system.
> 
> **How?**
> Mostly because of how we want it to be, rather than relying on GitHub for downloading the command, we want to have a custom external server to place commands in rbxm file. That way, we can implement update reviewing process, and more.
> 
> However, with that being said, not only we need a server to handle the backend, but we also need a powerful file server and a database server as well, which means there will be **three** servers in total.
> 
> As Commander is open-source, completely free and does not have any actual backers to help us with funding, it is barely possible for us to afford the operating cost for those three servers.

I understand your issue, have you considered using Heroku? They give around 1000 Dyno (server) hours free which could alleviate the costs even by a bit.

**Comment by va1kio** [comment]
We have considered it, actually! But the specs with the free plan is quite limited.

My goto at this is probably wait until Commander becomes huger, then we will apply for the open-sourced "perks" in some of the VPS host, like Vercel.

**Comment by Ivanmatthew** [comment]
Alright, I will close the comment now. Good luck with the admin
